//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Hack.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HackParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IHackListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] HackParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] HackParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddress([NotNull] HackParser.AddressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.address"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddress([NotNull] HackParser.AddressContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.compute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompute([NotNull] HackParser.ComputeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.compute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompute([NotNull] HackParser.ComputeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] HackParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] HackParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] HackParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] HackParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] HackParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] HackParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp([NotNull] HackParser.CompContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.comp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp([NotNull] HackParser.CompContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDest([NotNull] HackParser.DestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.dest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDest([NotNull] HackParser.DestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HackParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump([NotNull] HackParser.JumpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HackParser.jump"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump([NotNull] HackParser.JumpContext context);
}
