//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HDL.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHDLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class HDLBaseListener : IHDLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.chip"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChip([NotNull] HDLParser.ChipContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.chip"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChip([NotNull] HDLParser.ChipContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] HDLParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] HDLParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPart([NotNull] HDLParser.PartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPart([NotNull] HDLParser.PartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.partName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartName([NotNull] HDLParser.PartNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.partName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartName([NotNull] HDLParser.PartNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.chipName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChipName([NotNull] HDLParser.ChipNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.chipName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChipName([NotNull] HDLParser.ChipNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pinName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPinName([NotNull] HDLParser.PinNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pinName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPinName([NotNull] HDLParser.PinNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pinWidth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPinWidth([NotNull] HDLParser.PinWidthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pinWidth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPinWidth([NotNull] HDLParser.PinWidthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.connections"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnections([NotNull] HDLParser.ConnectionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.connections"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnections([NotNull] HDLParser.ConnectionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.conn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConn([NotNull] HDLParser.ConnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.conn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConn([NotNull] HDLParser.ConnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.inputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputs([NotNull] HDLParser.InputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.inputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputs([NotNull] HDLParser.InputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutputs([NotNull] HDLParser.OutputsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.outputs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutputs([NotNull] HDLParser.OutputsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPin([NotNull] HDLParser.PinContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPin([NotNull] HDLParser.PinContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
