//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HDL.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HDLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IHDLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.chip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChip([NotNull] HDLParser.ChipContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.chip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChip([NotNull] HDLParser.ChipContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] HDLParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] HDLParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPart([NotNull] HDLParser.PartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPart([NotNull] HDLParser.PartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.partName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartName([NotNull] HDLParser.PartNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.partName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartName([NotNull] HDLParser.PartNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.chipName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChipName([NotNull] HDLParser.ChipNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.chipName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChipName([NotNull] HDLParser.ChipNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pinName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPinName([NotNull] HDLParser.PinNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pinName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPinName([NotNull] HDLParser.PinNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pinWidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPinWidth([NotNull] HDLParser.PinWidthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pinWidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPinWidth([NotNull] HDLParser.PinWidthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.connections"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnections([NotNull] HDLParser.ConnectionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.connections"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnections([NotNull] HDLParser.ConnectionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.conn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConn([NotNull] HDLParser.ConnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.conn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConn([NotNull] HDLParser.ConnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.inputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputs([NotNull] HDLParser.InputsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.inputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputs([NotNull] HDLParser.InputsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.outputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputs([NotNull] HDLParser.OutputsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.outputs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputs([NotNull] HDLParser.OutputsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HDLParser.pin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPin([NotNull] HDLParser.PinContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HDLParser.pin"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPin([NotNull] HDLParser.PinContext context);
}
